"""drop article_category table

Revision ID: 03473b0382e8
Revises: 365520ec8207
Create Date: 2024-07-23 12:07:10.734937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03473b0382e8'
down_revision = '365520ec8207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_category',
    sa.Column('id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('parent_id', mysql.VARCHAR(length=40), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['article_category.id'], name='article_category_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
