"""Thumbnail Null True

Revision ID: 0db80ed0ffff
Revises: f521827a7bea
Create Date: 2024-07-07 10:47:23.420572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0db80ed0ffff'
down_revision = 'f521827a7bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('thumbnail',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('thumbnail',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)

    # ### end Alembic commands ###
