"""tag_to_category

Revision ID: 1880b29828b1
Revises: adac62538055
Create Date: 2024-07-16 15:13:45.772417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1880b29828b1'
down_revision = 'adac62538055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=80), nullable=True))
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', mysql.VARCHAR(length=300), nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
