"""delete category_id from article

Revision ID: 365520ec8207
Revises: cf3cd818634d
Create Date: 2024-07-23 12:02:56.268637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '365520ec8207'
down_revision = 'cf3cd818634d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint('article_ibfk_1', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.VARCHAR(length=40), nullable=False))
        batch_op.create_foreign_key('article_ibfk_1', 'article_category', ['category_id'], ['id'])

    # ### end Alembic commands ###
