"""Order_num Column ADD

Revision ID: 485e077b27fa
Revises: b0294c4e3989
Create Date: 2024-07-22 12:47:33.715796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485e077b27fa'
down_revision = 'b0294c4e3989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sql_doc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_num', sa.Integer(), nullable=False))

    with op.batch_alter_table('sql_doc_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_num', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sql_doc_category', schema=None) as batch_op:
        batch_op.drop_column('order_num')

    with op.batch_alter_table('sql_doc', schema=None) as batch_op:
        batch_op.drop_column('order_num')

    # ### end Alembic commands ###
