"""Modify Article Category Column Name

Revision ID: 6d8834990e81
Revises: fdb966ef7415
Create Date: 2024-07-20 07:49:35.751499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d8834990e81'
down_revision = 'fdb966ef7415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=200), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
