"""Article Category Table

Revision ID: cf3cd818634d
Revises: 485e077b27fa
Create Date: 2024-07-22 22:28:26.478474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf3cd818634d'
down_revision = '485e077b27fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_category',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['article_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.String(length=40), nullable=False))
        batch_op.create_foreign_key(None, 'article_category', ['category_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=60), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('article_category')
    # ### end Alembic commands ###
