"""Article Tags

Revision ID: fdb966ef7415
Revises: f2fb456c3f72
Create Date: 2024-07-20 07:43:47.385846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdb966ef7415'
down_revision = 'f2fb456c3f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_tags')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('tag')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=300), nullable=True))

    with op.batch_alter_table('sql_doc', schema=None) as batch_op:
        batch_op.drop_constraint('sql_doc_ibfk_2', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sql_doc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', mysql.VARCHAR(length=40), nullable=True))
        batch_op.create_foreign_key('sql_doc_ibfk_2', 'sql_doc', ['parent_id'], ['id'])

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('tags')

    op.create_table('tag',
    sa.Column('id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('article_tags',
    sa.Column('article_id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('tag_id', mysql.VARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name='article_tags_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='article_tags_ibfk_2'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
